{
 "title": "Simple Data Source",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество потоков ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "ThreadCount", "type": "timeserie" }
   ]
  },
  {
   "title": "Время выполнения текущей операции (загрузка, рендеринг, экспорт, макрос)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "Parameters", "type": "timeserie" }
   ]
  },
  {
   "title": "График производительности в разрезе потоков",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "target": "Threads", "type": "timeserie" }
   ]
  },
  {
   "title": "Список отчетов. Максимальное время выполнения каждого отчета за период",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "ReportDuration", "type": "timeserie" }
   ]
  },
  {
   "title": "График производительности в разрезе операций",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "target": "Operations", "type": "timeserie" }
   ]
  },
  {
   "title": "Список отчетов. Количество отчетов за период",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "ReportCount", "type": "timeserie" }
   ]
  }
 ]
}