{
 "title": "Мониторинг серверов отчетов",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ad_hoc_filter", "label": "Фильтр" },
   { "name": "server_report", "label": "Сервера отчетов", "query": "grafana-simple-json-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Текущие выполняемые отчеты",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "CurrentReportDuration", "type": "timeserie" }
   ]
  },
  {
   "title": "ТОП отчетов с максимальным временем выполнения  за период",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "DoneReportDuration", "type": "timeserie" }
   ]
  },
  {
   "title": "Количество потоков ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "ThreadCount", "type": "timeserie" }
   ]
  },
  {
   "title": "Время выполнения последней текущей операции (загрузка, рендеринг, экспорт, макрос)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "LastOperations", "type": "timeserie" }
   ]
  },
  {
   "title": "График производительности в разрезе потоков",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "target": "Threads", "type": "timeserie" }
   ]
  },
  {
   "title": "График производительности в разрезе операций",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "target": "Operations", "type": "timeserie" }
   ]
  },
  {
   "title": "ТОП отчетов с максимальным количеством за период",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "DoneReportCount", "type": "timeserie" }
   ]
  }
 ]
}